fuel_checker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('map.urls')),
    path('accounts/login/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('tracker/', include('tracker.urls')),
]

map/urls.py
from django.urls import path

from . import views

app_name = 'map'
urlpatterns = [
    path('', views.index, name='index'),
]

tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'
urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.addTracker, name="add"),
    path('complete/<tracker_id>', views.completeTracker, name="complete"),
    path('deletecomplete', views.deleteCompleted, name="deletecomplete"),
    path('deleteall', views.deleteAll, name="deleteall")
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login_view', views.login_view, name='login_view'),
    path('logout_view', views.logout_view, name='logout_view'),
]

map/models.py
from django.db import models

# Create your models here.

tracker/models.py
from django.db import models

# Create your models here.
class Tracker(models.Model):
    text = models.CharField(max_length=60)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.text

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    captcha_score = models.FloatField(default = 0.0)

tracker/forms.py
from django import forms

class TrackerForm(forms.Form):
    text = forms.CharField(max_length=40, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Station @ price", 'aria-label': 'Todo', 'aria-describedby':'add-btn'}))

map/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    return render(request, 'map/index.html')

tracker/views.py
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST
from .forms import TrackerForm
from .models import Tracker

# Create your views here.
def index(request):
    tracker_list = Tracker.objects.order_by('id')
    form = TrackerForm
    context = {'tracker_list': tracker_list, "form": form}
    return render(request, 'tracker/index.html', context)

@require_POST
def addTracker(request):
    form = TrackerForm(request.POST)

    print(request.POST['text'])

    if form.is_valid():
        new_tracker = Tracker(text=request.POST['text'])
        new_tracker.save()

    return redirect('tracker:index')


def completeTracker(request, tracker_id):
    tracker = Tracker.objects.get(pk=tracker_id)
    tracker.complete = True
    tracker.save()

    return redirect('tracker:index')


def deleteCompleted(request):
    Tracker.objects.filter(complete__exact=True).delete()

    return redirect('tracker:index')


def deleteAll(request):
    Tracker.objects.all().delete()

    return redirect('tracker:index')

users/views.py
from django.http import HttpResponseRedirect
from .models import User
from django.db import IntegrityError
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login_view'))
    return render(request, 'users/user.html')


def login_view(request):
    if request.method =='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'invalid credentials.'
            })

    return render(request, "users/login.html")


def logout_view(request):
    logout(request)

    return render(request, 'users/login.html', {
        'message': 'Logged out'
    })


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "users/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "users/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("users:index"))
    else:
        return render(request, "users/register.html")

map/templates/map/index.html
{% load static %}
<html>
  <head>
    <title>Maps</title>
    <script
      src="https://code.jquery.com/jquery-3.6.1.min.js"
      integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'users:index' %}">Fuel Check</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'users:index' %}"
            >Home<span class="sr-only">(current)</span></a
          >
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'tracker:index' %}"
            >Tracker</a
          >
          <a class="nav-item nav-link" href="{% url 'map:index' %}">Map</a>
          <a class="nav-item nav-link" href="{% url 'users:logout_view' %}"
            >Logout</a
          >
          {% else %}
          <a class="nav-item nav-link" href="{% url 'users:login_view' %}"
            >Log In</a
          >
          <a class="nav-item nav-link" href="#">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
      <div id="map" style="height: 100%; width: 100%"></div>
    </div>
    <script async src="{% static 'script.js' %}"></script>
    <script
      async
      defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmDZeUiC1faUA4am7r7oZggdRMyvnOl6s&libraries=places&callback=initGoogle"
    ></script>
  </body>
</html>

tracker/templates/tracker/index.html
{% extends 'tracker/layout.html' %}
{% load static %}
	{% block body %}
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" style="width: 100%;">
				<div class="col-lg-4 col-lg-offset-4" id="content">
					<h2>Track Your Fuel Purchases</h2>
					
					<form action="{% url 'tracker:add' %}" method="POST" role="form">
						{% csrf_token %}
						<div class="form-group">
							<div class="input-group">
							  {{ form.text }}
							  <span class="input-group-btn">
								  <button type="submit" class="btn btn-warning" id="add-btn">ADD</button>
							  </span>
							</div>
						</div>
					</form>

					<div class="row t10">
						<div class="col-lg-12">
							<div class="btn-toolbar">
								<div class="btn-group">
									<a href="{% url 'tracker:deletecomplete' %}"><button type="button" class="btn btn-warning">
										<i class="glyphicon glyphicon-trash"></i> DELETE SELECTED
									</button></a>
								</div>
								<div class="btn-group">
									<a href="{% url 'tracker:deleteall' %}"><button type="button" class="btn btn-warning">
										<i class="glyphicon glyphicon-trash"></i> DELETE ALL
									</button></a>
								</div>
							</div>
						</div>
					</div>

					<ul class="list-group t20">
						{% for tracker in tracker_list %}
							{% if tracker.complete %}
							<li class="list-group-item tracker-completed">{{ tracker.text }}</li>
							{% else %}
							<a href="{% url 'tracker:complete' tracker.id %}"><li class="list-group-item">{{ tracker.text }}</li></a>
							{% endif %}
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
	{% endblock %}
	</body>
</html>

tracker/templates/tracker/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Map</title>
		    <link rel="stylesheet" href="{% static 'tracker/styles.css' %}" />
        <title>Maps</title>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'users:index' %}">Fuel Check</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'users:index' %}">Home<span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'tracker:index' %}">Tracker</a>
                <a class="nav-item nav-link" href="{% url 'map:index' %}">Map</a>
                <a class="nav-item nav-link" href="{% url 'users:logout_view' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'users:login_view' %}">Log In</a>
                <a class="nav-item nav-link" href="#">Register</a>
            {% endif %}
          </div>
        </div>
    </nav>
        {% block body %}
        {% endblock %}    
    </body>
</html>

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Users</title>
        <title>Maps</title>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'users:index' %}">Fuel Check</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'users:index' %}">Home<span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'tracker:index' %}">Tracker</a>
                <a class="nav-item nav-link" href="{% url 'map:index' %}">Map</a>
                <a class="nav-item nav-link" href="{% url 'users:logout_view' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'users:login_view' %}">Log In</a>
                <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
            {% endif %}
          </div>
        </div>
    </nav>
        {% block body %}
        {% endblock %}      
    </body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'users:login_view' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'users:register' %}">Register here.</a>

{% endblock %}

users/templates/users/register.html
{% extends "users/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'users:login_view' %}">Log In here.</a>

{% endblock %}

users/templates/users/user.html
{% extends 'users/layout.html' %} {% block body %}
<h1>Welcome, {{ request.user.first_name }}</h1>

<ul>
  <li>Username: {{ request.user.username }}</li>
  <li>Email: {{ request.user.email }}</li>
</ul>

<a href="{% url 'users:logout_view' %}">Log Out</a>

{% endblock %}